// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/rates/rates.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/rates/rates.go -destination=tests/mocks/rates_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "usdt-rate-service/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockRateProvider is a mock of RateProvider interface.
type MockRateProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRateProviderMockRecorder
	isgomock struct{}
}

// MockRateProviderMockRecorder is the mock recorder for MockRateProvider.
type MockRateProviderMockRecorder struct {
	mock *MockRateProvider
}

// NewMockRateProvider creates a new mock instance.
func NewMockRateProvider(ctrl *gomock.Controller) *MockRateProvider {
	mock := &MockRateProvider{ctrl: ctrl}
	mock.recorder = &MockRateProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateProvider) EXPECT() *MockRateProviderMockRecorder {
	return m.recorder
}

// FetchRates mocks base method.
func (m *MockRateProvider) FetchRates(ctx context.Context) (domain.Rate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRates", ctx)
	ret0, _ := ret[0].(domain.Rate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRates indicates an expected call of FetchRates.
func (mr *MockRateProviderMockRecorder) FetchRates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRates", reflect.TypeOf((*MockRateProvider)(nil).FetchRates), ctx)
}

// MockRateSaver is a mock of RateSaver interface.
type MockRateSaver struct {
	ctrl     *gomock.Controller
	recorder *MockRateSaverMockRecorder
	isgomock struct{}
}

// MockRateSaverMockRecorder is the mock recorder for MockRateSaver.
type MockRateSaverMockRecorder struct {
	mock *MockRateSaver
}

// NewMockRateSaver creates a new mock instance.
func NewMockRateSaver(ctrl *gomock.Controller) *MockRateSaver {
	mock := &MockRateSaver{ctrl: ctrl}
	mock.recorder = &MockRateSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateSaver) EXPECT() *MockRateSaverMockRecorder {
	return m.recorder
}

// SaveRates mocks base method.
func (m *MockRateSaver) SaveRates(ctx context.Context, rate domain.Rate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRates", ctx, rate)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRates indicates an expected call of SaveRates.
func (mr *MockRateSaverMockRecorder) SaveRates(ctx, rate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRates", reflect.TypeOf((*MockRateSaver)(nil).SaveRates), ctx, rate)
}
